name: Generate SBOM

on:
  schedule:
    - cron: '0 6 1 * *'  # At 06:00 on the 1st of every month
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  generate-sbom:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install CycloneDX CLI
        run: |
          curl -s https://cyclonedx.org/install.sh | sh

      - name: Generate SBOM (JSON)
        run: |
          cyclonedx-npm --output-format json --output-file sbom.json

      - name: Generate SBOM (XML)
        run: |
          cyclonedx-npm --output-format xml --output-file sbom.xml

      - name: Upload SBOM artifacts
        uses: actions/upload-artifact@v4
        with:
          name: sbom-files
          path: |
            sbom.json
            sbom.xml
